
CREATE DATABASE IF NOT EXISTS crud DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci;;
USE crud;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
  idUser      INT PRIMARY KEY AUTO_INCREMENT,
  firstname   VARCHAR(20) NOT NULL,
  lastname    VARCHAR(20) NOT NULL,
  email       VARCHAR(60) UNIQUE NOT NULL,
  username    VARCHAR(40) UNIQUE NOT NULL,
  password    VARCHAR(80) NOT NULL
);

DROP TABLE IF EXISTS tasks;
CREATE TABLE tasks (
  idTask      INT PRIMARY KEY AUTO_INCREMENT,
  title       VARCHAR(80) NOT NULL,
  description TEXT NOT NULL,
  idUser      INT NOT NULL,
  createdAt   DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tasks ADD CONSTRAINT fk_tasks_users FOREIGN KEY (idUser) REFERENCES users (idUser) ON UPDATE CASCADE ON DELETE CASCADE;